export const SCREENS = {
  START_SCREEN: "START_SCREEN",
  LOGIN_SCREEN: "LOGIN_SCREEN",
  SIGNUP_SCREEN: "SIGNUP_SCREEN",
  DASHBOARD_SCREEN: "DASHBOARD_SCREEN",
  INTERRUPTIONS_SCREEN: "INTERRUPTIONS_SCREEN",
};
