export const SCREENS = {
  START_SCREEN: "START_SCREEN",
  LOGIN_SCREEN: "LOGIN_SCREEN",
  SIGNUP_SCREEN: "SIGNUP_SCREEN",
  FORGOT_PWD_SCREEN_1: "FORGOT_PWD_SCREEN_1",
  FORGOT_PWD_SCREEN_2: "FORGOT_PWD_SCREEN_2",
  FORGOT_PWD_SCREEN_3: "FORGOT_PWD_SCREEN_3",
  DASHBOARD_SCREEN: "DASHBOARD_SCREEN",
  INTERRUPTIONS_SCREEN: "INTERRUPTIONS_SCREEN",
  MANAGE_ACCOUNTS: "MANAGE_ACCOUNTS",
  EBILL_SERVICES: "EBILL_SERVICE"
};
