export const SCREENS = {
  START_SCREEN: "START_SCREEN",
  LOGIN_SCREEN: "LOGIN_SCREEN",
  SIGNUP_SCREEN: "SIGNUP_SCREEN",
  DASHBOARD_SCREEN: "DASHBOARD_SCREEN",
  INTERRUPTIONS_SCREEN: "INTERRUPTIONS_SCREEN",
  MANAGE_ACCOUNTS: "MANAGE_ACCOUNTS",
  EBILL_SERVICES: "EBILL_SERVICE"
};
